# -*- coding: utf-8 -*-
"""logistic_regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10nDHB6g_KhFNkz6JKf7u_abbUd2mkiX0

<h2 style="color:green" align="center">Predicting if a person would buy life insurnace based on his age using logistic regression</h2>

Above is a binary logistic regression problem as there are only two possible outcomes (i.e. if person buys insurance or he/she doesn't).
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
import math

st.set_page_config(page_title="Insurance Prediction", page_icon="📊")

st.title("📊 Life Insurance Prediction using Logistic Regression")
st.write("Predict whether a person will buy life insurance based on age.")

# Load dataset
df = pd.read_csv("insurance_data.csv")

st.subheader("Dataset")
st.dataframe(df)

# Scatter Plot
st.subheader("Age vs Bought Insurance")

fig, ax = plt.subplots()
ax.scatter(df["age"], df["bought_insurance"], marker="+", color="red")
ax.set_xlabel("Age")
ax.set_ylabel("Bought Insurance")
st.pyplot(fig)

# Train Model
X = df[["age"]]
y = df["bought_insurance"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, train_size=0.8, random_state=42
)

model = LogisticRegression()
model.fit(X_train, y_train)

accuracy = model.score(X_test, y_test)

st.subheader("Model Accuracy")
st.success(f"Accuracy: {accuracy:.2f}")

st.subheader("Model Parameters")
st.write("Coefficient:", model.coef_[0][0])
st.write("Intercept:", model.intercept_[0])

# User Input
st.subheader("Predict Insurance Purchase")

age = st.slider("Select Age", 18, 100, 35)

if st.button("Predict"):
    prediction = model.predict([[age]])[0]
    probability = model.predict_proba([[age]])[0][1]

    st.write(f"Probability of Buying Insurance: **{probability:.2%}**")

    if prediction == 1:
        st.success("✅ Person is likely to BUY insurance.")
    else:
        st.error("❌ Person is NOT likely to BUY insurance.")


# Sigmoid Function
st.subheader("Sigmoid Function (Manual Calculation)")

def sigmoid(x):
    return 1 / (1 + math.exp(-x))

z = model.coef_[0][0] * age + model.intercept_[0]
manual_probability = sigmoid(z)

st.write(f"Sigmoid Output: **{manual_probability:.4f}**")

"""<h2 style="color:purple">Exercise</h2>

Download employee retention dataset from here: https://www.kaggle.com/giripujar/hr-analytics.
1. Now do some exploratory data analysis to figure out which variables have direct and clear impact on employee retention (i.e. whether they leave the company or continue to work)
2. Plot bar charts showing impact of employee salaries on retention
3. Plot bar charts showing corelation between department and employee retention
4. Now build logistic regression model using variables that were narrowed down in step 1
5. Measure the accuracy of the model
"""